[package]
name = "client"
version = "0.1.0"
authors = ["valeev-aidar <ai.valeev@innopolis.ru>"]

[dependencies]
# network
reqwest = "0.8"

# GUI
pancurses = "0.12"

# serde
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
base64 = "0.7.0"
